### ISSUE TITLE
Tandem Repeat Finder

### ISSUE THREAD

**Issue by andyb3** [WGLab/RepeatHMM#13]
Hi (sorry me again!). Quick question, when using a predefined repeat (e.g. HTT) by supplying the `--repeatName` argument, is tandem repeat finder (TRF) still needed and/or used?

When running repeatHMM using the  `--repeatName HTT` argument without TRF installed, the following error message is output `sh: trf: command not found`. However repeatHMM still completes and produces a sensible result.

It makes sense that TRF wouldnt be needed if you already know what repeat you're looking for. However upon installing TRF, the error message goes away and the time taken for repeatHMM to run increases somewhat implying TRF is still being used, however the output of repeatHMM is unchanged.

Many thanks,
Andy

**Comment by liuqianhn** [comment]
Hi @andyb3 , I am happy to answer any question for using this tool. TRF is necessary for running repeatHMM even `--repeatName HTT` is provided. TRF is not used to find repeat in a reference genome but for long reads.

It is possible that the results are similar/same with/without TRF, if the repeat regions in long reads are short. But if there are many very long repeat regions (hundreds or even thousands kb), there would be a big difference with/without TRF. I am not sure whether your data only have short repeat region. Please feel free to share it if possible. Thank you.

**Comment by andyb3** [comment]
OK thanks very much for the clarification. Yes our data has relatively short repeats, we're just looking at the CAG repeat in HTT. 

Many thanks, 
Andy
