### ISSUE TITLE
strand parameter in user defined repeat

### ISSUE THREAD

**Issue by drumdum** [WGLab/RepeatHMM#15]
Hi RepeatHMM-Team,

while I played around with the user defined repeat parameter, I came to a question about the strand value that needs to be given. As my experiments show, the only difference is between positive and negative values. So there is no difference in the output between -1 and -10, or +1 and +5. Is that right?

Could you please clarify what the strand parameter stands for. I could not find any hint in the documentation, but the predefined repeats all have a 
distinct strand value defined.

I've attached a short log of my experiment: 
[RepeatHMM_experiment.log](https://github.com/WGLab/RepeatHMM/files/2388088/RepeatHMM_experiment.log)

**Comment by liuqianhn** [comment]
Hi @drumdum, Thank you for being interested in our tool. 

Regarding the strand parameter,  only "+" or "-" is used in the tool, and the other numbers (1, 5, 10 in your parameters) following "+"/"-" is blind to the prediction.  

"+" suggests a motif in the forward strand and "-" means in the reverse strand.

**Comment by drumdum** [comment]
Thanks for the clarification.
