### ISSUE TITLE
Question on customised files

### ISSUE THREAD

**Issue by liutiming** [WGLab/RepeatHMM#19]
I would like to include my own csv file for analysis. Can I ask what should I put for the strand column, please? I am not sure what does the number after the +/- sign mean in the hg38.predefined.pa file (e.g. what does 15 mean in the line

>  aff2,chrX,148500606,148500692,CCG,+15,6-35:200+, 

?

Thank you!

**Comment by liutiming** [comment]
https://github.com/WGLab/RepeatHMM/issues/15#issuecomment-422163305

Ok I found the solution here. I will give it a try.

**Comment by liutiming** [comment]
Hello I have encountered some issues (error no information) when using my own customised firles. Can I ask:
1. where should the csv files be placed
2. do we need to include the commas for the columns that are not necessary (i.e. 6th columns and above)
3. could you please provide a sample command of using a customised file when running repeatHMM in RepeatHMM/bin/ please?

Thank you!

**Comment by liuqianhn** [comment]
Hi @6timings , sorry for late reply. In your customized file, you need all information as "#0.Name, 1.chr, 2.start-pos, 3.end-pos, 4.pattern, 5.strand, 6.range, 7.others". Only the last two fields are optional but you need to leave them empty.  When you run with your customized file, you need to add "--Patternfile full-path-of-your-customized file" to your running commands. Please let me any issue if you have.

**Comment by liuqianhn** [comment]
Hi @6timings , you can also specify more than one files for "--Patternfile" and filenames are split by ';'
