### ISSUE TITLE
RepeatHMM and RepeatCCS

### ISSUE THREAD

**Issue by wenluo711** [WGLab/RepeatHMM#24]
Hi, 
I ran RepeatHMM on both raw pacbio raw and ccs bam files(pcr amplified target sequence) but results are quite different. 
Here is the raw bam file result:
CompRepPatc G/AlG/AlG/AlG/A [{'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}]
The following options are used (included default):
       BWAMEMOptions	( -k8 -W8 -r7 );
             CompRep	([{'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}]);
           MatchInfo	([3, -2, -2, -15, -1]);
              MaxRep	(4000);
              MinSup	(3);
         Patternfile	(['/CGF/Bioinformatics/Production/Wen/20190528_repeat_expanding_calling_pacbio_23569/hg19_repeat_region.UCSC.pa']);
          RepeatTime	(5);
             SeqTech	(Pacbio);
     SplitAndReAlign	(1);
          TRFOptions	(2_7_4_80_10_100);
   Tolerate_mismatch	(None);
   UserDefinedUniqID	(SB635220.UCSC);
               align	(align/);
           emissionm	(None);
                  hg	(hg19);
              hgfile	(/CGF/Bioinformatics/Production/Wen/20190528_repeat_expanding_calling_pacbio_23569/hg19_canonical_correct_chr_order.fa);
        hmm_del_rate	(0.02);
     hmm_insert_rate	(0.11);
        hmm_sub_rate	(0.02);
     isGapCorrection	(1);
       minRepBWTSize	(70);
         minTailSize	(70);
              outlog	(2);
   repeatFlankLength	(30);
p2sp ['rn7sl554p', 22.5, [13, 38], 'allocr:0:23, 2:12, 3:22, 4:10, 5:2, 6:82, 7:12, 8:35, 9:41, 10:12, 11:15, 12:213, 13:224, 14:18, 15:18, 16:17, 17:79, 18:191, 19:134, 20:84, 21:81, 22:93, 23:80, 24:48, 25:22, 26:16, 27:16, 28:11, 29:6, 30:9, 31:7, 32:8, 33:17, 34:47, 35:112, 36:164, 37:147, 38:127, 39:113, 40:111, 41:100, 42:59, 43:38, 44:19, 45:12, 46:11, 47:6, 48:4, 49:9, 50:2, 51:3, 52:2, 53:9, 54:4, 55:6, 56:7, 57:4, 58:2, 59:4, 60:3, 61:3, 62:5, 63:2, 65:2, 66:1, 67:1, 68:1, 71:2, 72:1, 73:2, 78:1, 82:1, 84:1, 89:1, 94:1, 102:1, 135:1, 201:1, 202:1, 489:1,', 2813, 248]

Here is the CCS bam result:
CompRepPatc G/AlG/AlG/AlG/A [{'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}]
The following options are used (included default):
       BWAMEMOptions	( -k8 -W8 -r7 );
             CompRep	([{'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}, {'A': 0.5, 'G': 0.5}]);
           MatchInfo	([3, -2, -2, -15, -1]);
              MaxRep	(4000);
              MinSup	(3);
         Patternfile	(['/CGF/Bioinformatics/Production/Wen/20190528_repeat_expanding_calling_pacbio_23569/hg19_repeat_region.UCSC.pa']);
          RepeatTime	(5);
             SeqTech	(Pacbio);
     SplitAndReAlign	(1);
          TRFOptions	(2_7_4_80_10_100);
   Tolerate_mismatch	(None);
   UserDefinedUniqID	(SB635220.UCSC);
               align	(align/);
           emissionm	(None);
                  hg	(hg19);
              hgfile	(/CGF/Bioinformatics/Production/Wen/20190528_repeat_expanding_calling_pacbio_23569/hg19_canonical_correct_chr_order.fa);
        hmm_del_rate	(0.02);
     hmm_insert_rate	(0.11);
        hmm_sub_rate	(0.02);
     isGapCorrection	(1);
       minRepBWTSize	(70);
         minTailSize	(70);
              outlog	(2);
   repeatFlankLength	(30);
 p2sp ['rn7sl554p', 22.5, [12, 13], 'allocr:6:4, 9:1, 12:25, 13:1036, 36:1, 39:1,', 1068, 2]

According to the RepeatHMM paper, these two performed very close. I'm wondering if there were any bam file qc or normalization performed on the raw or ccs bam files before running repeatHMM or should I be using different parameters for ccs reads and raw reads?

Thanks, 
Wen

**Comment by liuqianhn** [comment]
Hi @wenluo711 , I do not use any qc or normalization before running repeatHMM and also not use different parameters for ccs/raw reads. I usually use the results from raw results. But repeatHMM on your ccs data give quite different repeat distribution which I have no idea why now. More investigation of your data might be needed. Meanwhile, it would also be great if you can share the repeat region you are investigated. Thank you.

**Comment by wenluo711** [comment]
Thanks! @liuqianhn 
This is the region we are interested:

https://genome.ucsc.edu/cgi-bin/hgc?hgsid=727407937_NiP6MIBBAlic6yDeCOakP6PMy6AK&c=chr6&l=6836788&r=6837688&o=6837193&t=6837283&g=simpleRepeat&i=trf

Looks like our pcr amplified reads do have some specific profiles....

Thanks for the comment.
Wen

**Comment by liuqianhn** [comment]
Hi @wenluo711 , sorry that I seems I missed your comments here. Please let me know if I still can help anything here.

**Comment by wenluo711** [comment]
Hi @liuqianhn , I did get what I was asking. Just wanted to know if you have any preprocessing or qc step on your ccs/raw data before running repeatHMM. Our data seems wierd that each of our 8 sample is getting same repeatHMM result of [12,13] or [13,13] for ccs data given the repeat region above. 
Like you said, more investigation might be needed. 

Thanks!
Wen
