### ISSUE TITLE
MinION data

### ISSUE THREAD

**Issue by woodoo46** [WGLab/RepeatHMM#26]
Hi there,

Do we need to do some special processing for MinION data?

Thanks.

**Comment by liuqianhn** [comment]
Hi @woodoo46 , you can set ``--hmm_insert_rate`, `--hmm_del_rate` and `--hmm_sub_rate` for insertion error rate, deletion error rate and mismatch error rates for specific sequencing platform, which might improve the performance but not fully tested.

**Comment by woodoo46** [comment]
Do you have recommended settings for MinION data? Thanks.

**Comment by liuqianhn** [comment]
I have no optimized settings for MinION data.  But you can set insertion rate as 0.03, deletion rate as 0.05 and mismatch as 0.06. But there is no guarantee that the parameters are optimal.

**Comment by woodoo46** [comment]
These settings are not data error rate, right? They are for hmm parameters?

**Comment by liuqianhn** [comment]
@woodoo46 , they would be data error rates. So, it would be better if you could provide optimal error rate based on your data, although usually it does not affect the results significantly.
