### ISSUE TITLE
How to use paired end fastq reads for RepeatHMM

### ISSUE THREAD

**Issue by amrita1983** [WGLab/RepeatHMM#28]
Hi,

I  am trying to find out HTT repeats in known sample, but when I am using the bam file generated using BWA local mode, it is not showing any repeat at all. I am very surprised with the output.
I thought of using the fastq file directly, but did not find out how to use paired end illumina WGS data for it. 
Command: python2 repeatHMM.py BAMinput --Onebamfile HD_aligned.sorted.bam --hg hg19 --hgfile /home/ngs/Downloads/RepeatHMM/bin/ref/hg/hg19.fa --repeatName all

It is extremely urgent to get the result for me as I have a conference next week it would be great if you can help me.

**Comment by liuqianhn** [comment]
Hi @amrita1983 , RepeatHMM is not designed to work on paired end reads. you can add `--GapCorrection 0 --FlankLength 15 --MinSup 3 --SplitAndReAlign 0` with a bam so that RepeatHMM might output some repeats, but paired end information is not used and each read is considered separately.

**Comment by amrita1983** [comment]
Thank you for the reply, but still the tool is not able to detect any repeat expansion from the BAM file using the options that you have mentioned. I will try using fastq file once.

**Comment by liuqianhn** [comment]
If you want, could you please get a bam for a specific repeat region and the repeat region information and the bam file to me for testing? Thank you.

**Comment by liuqianhn** [comment]
Closed due to no recent activities.
