### ISSUE TITLE
No pa file  reference_sts//hg38/hg38.predefined.pa

### ISSUE THREAD

**Issue by woodoo46** [WGLab/RepeatHMM#29]
When I ran the program, I got this message:

No pa file  reference_sts//hg38/hg38.predefined.pa

Is this important?

**Comment by liuqianhn** [comment]
Hi @woodoo46 , it depends on your input, and usually it is important. It is in "RepeatHMM/bin/reference_sts//hg38/hg38.predefined.pa", you might provide the full path name if you run RepeatHMM out RepeatHMM/bin folder.

**Comment by woodoo46** [comment]
My input is bamfile and a user defined interesting region. I guess file reference_sts//hg38/hg38.predefined.pa contains some predefined regions?

**Comment by woodoo46** [comment]
So for a user-defined region, the pa file is not important?

**Comment by liuqianhn** [comment]
Hi @woodoo46 , yes, the pa file contains predefined repeat regions, and for user-defined regions, the pa file is not important, but it will be read by default.

**Comment by liuqianhn** [comment]
Closed due to no recent activities.
