### ISSUE TITLE
KeyError: 'rep_flanking_data'

### ISSUE THREAD

**Issue by cangfengzhe** [WGLab/RepeatHMM#3]
File "./RepeatHMM/bin/scripts/myBAMhandler.py", line 199, in getUnsymAlignAndHMM
rep_predata, rep_sufdata = commonOptions['rep_flanking_data']
KeyError: 'rep_flanking_data'

运行时出现上述错误，查看源码发现， commonOptions['rep_flanking_data'] 仅在 RepeatHMM/bin/scripts/myBAMhandler.py 出现两次
1. 
```
def getUnsymAlignAndHMM(repPat, forw_rerv, repeatFlankLength, hmmoptions, queryrep, commonOptions, otherinfo):
        rep_predata, rep_sufdata = commonOptions['rep_flanking_data']
```
该处是报错的位置

2. 
```
def getRepeatForGivenGene(commonOptions, specifiedOptions, moreOptions):
......
    commonOptions['rep_flanking_data'] = rep_predata, rep_sufdata
```
该处有赋值
对 commonOptions['rep_flanking_data'] 进行赋值，仅仅是局部变量赋值

请帮助解决上述问题，谢谢。

**Comment by liuqianhn** [comment]
你好。 已经赋值。 commonOptions会被传递到getUnsymAlignAndHMM， 所以局部变量赋值在getUnsymAlignAndHMM中可以被使用。 请更新文件。多谢。

**Comment by cangfengzhe** [comment]
这个问题已经解决了，谢谢。来北京的话，可以请你吃饭，哈哈哈
