### ISSUE TITLE
Low number of reads mapping and access to bam files

### ISSUE THREAD

**Issue by pcr1120** [WGLab/RepeatHMM#31]
Hi, 
We are analyzing ATXN2 CAG repeats
We have 91963 reads but the result shows CAG repeat only in 1316 sequences. Routine mappers are picking up more CAGs. Why is the number from RepeatHMM so low? 

Is it possible to generate the bam files and look the sequences around the repeats??

Thanks

**Comment by liuqianhn** [comment]
Hi @pcr1120 , I have no idea about this issue now. One possible reason is that many reads are partially aligned against the repeat regions, and RepeatHMM will not use them. RepeatHMM also provides the module to directly detect repeats from BAM without re-alignment. But it does not solve the issue of partial alignment of repeat regions.. Thus, it would be great if you can provide more information, for example, the last 30 lines in the RepeatHMM log file, and how many reads you can find around the repeat region.

**Comment by pcr1120** [comment]
HI,
Thanks for the prompt response

We do expect some sequence variation around the repeats, how do you recommend we handle partial matches?

here is what our result file looks like
Thanks

The following options are used (included default):
       BWAMEMOptions	( -k8 -W8 -r7 );
             CompRep	(0);
           MatchInfo	([3, -2, -2, -15, -1]);
              MaxRep	(4000);
              MinSup	(5);
         Patternfile	(None);
          RepeatTime	(5);
             SeqTech	(None);
     SplitAndReAlign	(1);
          TRFOptions	(2_7_4_80_10_100);
   Tolerate_mismatch	(None);
   UserDefinedUniqID	(None);
               align	(align/);
           emissionm	(None);
                  hg	(hg38);
              hgfile	(/home/microbe_hunter/Documents/Chitra_data/2020/Jan_2020/Swathi_reanalyze/chr12.fa);
        hmm_del_rate	(0.02);
     hmm_insert_rate	(0.12);
        hmm_sub_rate	(0.02);
     isGapCorrection	(1);
       minRepBWTSize	(70);
         minTailSize	(70);
              outlog	(2);
   repeatFlankLength	(30);
          repeatName	(atxn2);
 specifiedRepeatInfo	(///////);
      stsBasedFolder	(reference_sts/);
         transitionm	(None);

               align	(align/);
    analysis_file_id	(_GapCorrection1_FlankLength30_SplitAndReAlign1_2_7_4_80_10_100_hg38_comp_I0.120_D0.020_S0.020);
           fastafile	(/home/microbe_hunter/Documents/Chitra_data/2020/Jan_2020/Swathi_reanalyze/test_bc01/barcode01/sw_bc01.fastq);
      unique_file_id	(.gmm_GapCorrection1_FlankLength30_SplitAndReAlign1_2_7_4_80_10_100_hg38_comp_I0.120_D0.020_S0.020);

p2sp end---running time377 mem136

for output

      p2sp ['atxn2', 23.0, [30, 30], 'allocr:0:57, 2:10, 3:18, 4:6, 5:20, 6:21, 7:21, 8:12, 9:24, 10:30, 11:27, 12:26, 13:31, 14:29, 15:36, 16:30, 17:46, 18:51, 19:61, 20:59, 21:64, 22:46, 23:32, 24:24, 25:33, 26:37, 27:53, 28:58, 29:63, 30:86, 31:94, 32:85, 33:86, 34:30, 35:17, 36:10, 37:3, 38:2, 39:1,', 1439, 135]

 	p2sp
atxn2	 30 30;

('The result is in', 'logfq/RepFQ_atxn2.gmm_GapCorrection1_FlankLength30_SplitAndReAlign1_2_7_4_80_10_100_hg38_comp_I0.120_D0.020_S0.020.log')

**Comment by liuqianhn** [comment]
Closed due to no recent response. Feel free to reopen it if you need more help.
