### ISSUE TITLE
ImportError: No module named _UnsymmetricPairAlignment

### ISSUE THREAD

**Issue by Tine-dk** [WGLab/RepeatHMM#32]
Hi. 
I followed the installation guide but I get this error when running the software:
ImportError: No module named _UnsymmetricPairAlignment

But I do have something called _UnsymmetricPairAlignment.cpython-37m-x86_64-linux-gnu.so under /RepeatHMM/bin/RepeatHMM_scripts/UnsymmetricPairAlignment.

I'm not sure how to solve the error. Any suggestion is very appreciated. :)

**Comment by liuqianhn** [comment]
@Tine-dk Do you do the following steps
```
cd bin/scripts/UnsymmetricPairAlignment
make
```

If yes, could you please show me what are under `RepeatHMM/bin/RepeatHMM_scripts/UnsymmetricPairAlignment`?

Meanwhile, which python are you use for repeatHMM?

**Comment by Tine-dk** [comment]
Yes, I did that step. 
The Python version in the environment I created is 2.7.18.  Is that alright?

Under the folder "UnsymmetricPairAlignment" there is the following content:
_init_.py
_init_.pyc
_UnsymmetricPairAlignment.cpython-37m-x86_64-linux-gnu.so
Makefile
setup.py
UnsymmetricPairAlignment.c
UnsymmetricPairAlignment.i
UnsymmetricPairAlignent.py
UnsymmetricPairAlignment.pyc
UnsymmetricPairAlignment_wrap.c
build/temp.linux-x86_64-3.7/UnsymmetricPairAlignment.o
build/temp.linux-x86_64-3.7/UnsymmetricPairAlignment_wrap.o

**Comment by liuqianhn** [comment]
It seems that your compilation results are different from mine: I have `_UnsymmetricPairAlignment.so` rather than `_UnsymmetricPairAlignment.cpython-37m-x86_64-linux-gnu.so`. Could you please rename your `.so` file to see what happen? I do not know why you have the different file now.

**Comment by Tine-dk** [comment]
I renamed the file but unfortunately, it does not solve the error.

`ImportError: /RepeatHMM/bin/RepeatHMM_scripts/UnsymmetricPairAlignment/_UnsymmetricPairAlignment.so: undefined symbol: PyUnicode_FromFormat`

**Comment by Tine-dk** [comment]
I think I solved it.
It was the order I did the installation steps in. 
If the UnsymmetricPairAlignment has been "made" before the environment has been created and activated, the error occurs.
Now I have the correct .so file.
