### ISSUE TITLE
ValueError: Gap opening penalty should be higher than gap extension penalty (or equal)

### ISSUE THREAD

**Issue by cangfengzhe** [WGLab/RepeatHMM#5]
RepeatHMM/bin/scripts/myBAMhandler.py

```
match, mismatch, gap, gap_extension = 2, -1, -1, -10
...
la = pairwise2.align.localms(curp[0], curp[1], match, mismatch, gap, gap_extension)
``` 

一般认为新开始一个gap，要比gap extension的难度大，所以罚分要多， 这里 gap 罚分设置了-1，gap_extension 设置了 -10， 逻辑上说不通，函数也报错了。

**Comment by liuqianhn** [comment]
在这个函数中gap_extension的罚分多是因为比对的序列相识度高，而且局部的indels少。 所以， 有个别indels很正常，但是有太多的indels说明这个局部比对时没有太多意义的。 

我之前用的Bio版本是1.66. 估计在新的Bio包中，pairwise2更新中增加了限制。 你可以使用1.66的Bio包或者简单使用match, mismatch, gap, gap_extension = 1, -1, -1, -1. 我也会更新这个设置。

**Comment by cangfengzhe** [comment]
ok，感谢您的帮助。
刚发现，已经有人提过这个问题了，抱歉。
