### ISSUE TITLE
No module named 'UnsymmetricPairAlignment

### ISSUE THREAD

**Issue by ghost** [WGLab/RepeatHMM#51]
when run the RepeatHMM software, python ./bin/repeatHMM.py  , show the error message : 

![image](https://user-images.githubusercontent.com/54733697/203014592-88758dea-5deb-426e-8331-2464a47bca63.png)

Installation process：
source activate RepeatHMM
1. Download RepeatHMM
git clone https://github.com/WGLab/RepeatHMM
2. Create conda environment.
cd RepeatHMM
conda env create -f environment.yml
source activate repeathmmenv
cd bin/RepeatHMM_scripts/UnsymmetricPairAlignment
make
cd ../../../

**Comment by liuqianhn** [comment]
@huangrongbioinfomation "UnsymmetricPairAlignment" is under "bin/RepeatHMM_scripts/UnsymmetricPairAlignment". Could you please show you have under 'bin/RepeatHMM_scripts/UnsymmetricPairAlignment/'? Meanwhile, I see 'base' conda environment is used in the screenshot. Please 'source activate repeathmmenv' or 'conda activate repeathmmenv' each time when you use RepeatHMM.

Meanwhile, you can try the command below under `bin/RepeatHMM_scripts/UnsymmetricPairAlignment`, and `bin/RepeatHMM_scripts`, and share what is the output

under `bin/RepeatHMM_scripts/UnsymmetricPairAlignment`: after type `python `, then, `import UnsymmetricPairAlignment`

under `bin/RepeatHMM_scripts/`: after type `python `, then, `from UnsymmetricPairAlignment import UnsymmetricPairAlignment`

**Comment by ghost** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已经收到邮件
