### ISSUE TITLE
Quick question regarding tandem repeat finder

### ISSUE THREAD

**Issue by andyb3** [WGLab/RepeatHMM#9]
Hi. Thanks for producing this extremely useful tool. I noticed that on 4th Jan you removed Tandem Repeat Finder from the dependencies doc (0713604fbaf7692906930070f7ef5316484e647c). Does this mean TRF is no longer used by repeatHMM?

**Comment by liuqianhn** [comment]
Hi @andyb3 , Sorry for the confusion. Tandem repeat finder is still needed and in default path. I just wanted to reduce the work of users.

**Comment by andyb3** [comment]
No problem! Thanks for clearing that up. Also I noticed samtools is required but is not listed in  docs/Install.md. Maybe that could be added in too?

**Comment by liuqianhn** [comment]
Hi @andyb3 You are right. I have added samtools in docs/Install.md. Thanks.

**Comment by andyb3** [comment]
Thanks!
